/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* top =  1  *)
(* src = "dsp_mult_post_synth_sim.v:17.1-25.10" *)
module dsp_mult(A, B, Z);
  (* src = "dsp_mult_post_synth_sim.v:18.24-18.25" *)
  input [19:0] A;
  wire [19:0] A;
  (* src = "dsp_mult_post_synth_sim.v:19.24-19.25" *)
  input [17:0] B;
  wire [17:0] B;
  (* src = "dsp_mult_post_synth_sim.v:20.24-20.25" *)
  output [37:0] Z;
  wire [37:0] Z;
  (* is_inferred = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_mult_post_synth_sim.v:23.16-23.21|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:253.6-257.5|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_map.v:38.35-55.10|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v:47.7-69.6" *)
  QL_DSP2_MULT #(
    .MODE_BITS(80'h00000000000000000000)
  ) Z_QL_DSP2_MULT_z (
    .a(A),
    .b(B),
    .f_mode(1'h0),
    .feedback(3'h0),
    .output_select(3'h0),
    .register_inputs(1'h0),
    .reset(1'hx),
    .unsigned_a(1'h1),
    .unsigned_b(1'h1),
    .z(Z)
  );
endmodule
