/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* top =  1  *)
(* src = "dsp_simd_post_synth_sim.v:17.1-35.10" *)
module simd_mult(clk, a0, b0, z0, a1, b1, z1);
  (* src = "dsp_simd_post_synth_sim.v:20.25-20.27" *)
  input [9:0] a0;
  wire [9:0] a0;
  (* src = "dsp_simd_post_synth_sim.v:24.25-24.27" *)
  input [9:0] a1;
  wire [9:0] a1;
  (* src = "dsp_simd_post_synth_sim.v:21.25-21.27" *)
  input [8:0] b0;
  wire [8:0] b0;
  (* src = "dsp_simd_post_synth_sim.v:30.15-30.22|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:312.5-316.4|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:253.6-257.5|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_map.v:105.34-122.10|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v:102.17-102.18" *)
  (* unused_bits = "19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37" *)
  wire [37:0] b0_QL_DSP2_MULT_b_z;
  (* src = "dsp_simd_post_synth_sim.v:25.25-25.27" *)
  input [8:0] b1;
  wire [8:0] b1;
  (* src = "dsp_simd_post_synth_sim.v:33.15-33.22|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:312.5-316.4|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:253.6-257.5|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_map.v:105.34-122.10|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v:102.17-102.18" *)
  (* unused_bits = "19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37" *)
  wire [37:0] b1_QL_DSP2_MULT_b_z;
  (* src = "dsp_simd_post_synth_sim.v:18.25-18.28" *)
  input clk;
  wire clk;
  (* src = "dsp_simd_post_synth_sim.v:22.25-22.27" *)
  output [18:0] z0;
  wire [18:0] z0;
  (* src = "dsp_simd_post_synth_sim.v:26.25-26.27" *)
  output [18:0] z1;
  wire [18:0] z1;
  (* is_inferred = 32'd1 *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:30.15-30.22|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:312.5-316.4|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:253.6-257.5|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_map.v:105.34-122.10|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v:110.7-132.6" *)
  QL_DSP2_MULT #(
    .MODE_BITS(80'h00000000000000000000)
  ) b0_QL_DSP2_MULT_b (
    .a({ 10'h000, a0 }),
    .b({ 9'h000, b0 }),
    .f_mode(1'h1),
    .feedback(3'h0),
    .output_select(3'h0),
    .register_inputs(1'h0),
    .reset(1'hx),
    .unsigned_a(1'h1),
    .unsigned_b(1'h1),
    .z(b0_QL_DSP2_MULT_b_z)
  );
  (* is_inferred = 32'd1 *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:33.15-33.22|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:312.5-316.4|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/mul2dsp.v:253.6-257.5|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_map.v:105.34-122.10|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v:110.7-132.6" *)
  QL_DSP2_MULT #(
    .MODE_BITS(80'h00000000000000000000)
  ) b1_QL_DSP2_MULT_b (
    .a({ 10'h000, a1 }),
    .b({ 9'h000, b1 }),
    .f_mode(1'h1),
    .feedback(3'h0),
    .output_select(3'h0),
    .register_inputs(1'h0),
    .reset(1'hx),
    .unsigned_a(1'h1),
    .unsigned_b(1'h1),
    .z(b1_QL_DSP2_MULT_b_z)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[18]),
    .E(1'h1),
    .Q(z0[18]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_1 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[17]),
    .E(1'h1),
    .Q(z0[17]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_10 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[8]),
    .E(1'h1),
    .Q(z0[8]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_11 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[7]),
    .E(1'h1),
    .Q(z0[7]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_12 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[6]),
    .E(1'h1),
    .Q(z0[6]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_13 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[5]),
    .E(1'h1),
    .Q(z0[5]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_14 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[4]),
    .E(1'h1),
    .Q(z0[4]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_15 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[3]),
    .E(1'h1),
    .Q(z0[3]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_16 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[2]),
    .E(1'h1),
    .Q(z0[2]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_17 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[1]),
    .E(1'h1),
    .Q(z0[1]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_18 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[0]),
    .E(1'h1),
    .Q(z0[0]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_2 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[16]),
    .E(1'h1),
    .Q(z0[16]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_3 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[15]),
    .E(1'h1),
    .Q(z0[15]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_4 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[14]),
    .E(1'h1),
    .Q(z0[14]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_5 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[13]),
    .E(1'h1),
    .Q(z0[13]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_6 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[12]),
    .E(1'h1),
    .Q(z0[12]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_7 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[11]),
    .E(1'h1),
    .Q(z0[11]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_8 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[10]),
    .E(1'h1),
    .Q(z0[10]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:29.5-30.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z0_sdffre_Q_9 (
    .C(clk),
    .D(b0_QL_DSP2_MULT_b_z[9]),
    .E(1'h1),
    .Q(z0[9]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[18]),
    .E(1'h1),
    .Q(z1[18]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_1 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[17]),
    .E(1'h1),
    .Q(z1[17]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_10 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[8]),
    .E(1'h1),
    .Q(z1[8]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_11 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[7]),
    .E(1'h1),
    .Q(z1[7]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_12 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[6]),
    .E(1'h1),
    .Q(z1[6]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_13 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[5]),
    .E(1'h1),
    .Q(z1[5]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_14 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[4]),
    .E(1'h1),
    .Q(z1[4]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_15 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[3]),
    .E(1'h1),
    .Q(z1[3]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_16 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[2]),
    .E(1'h1),
    .Q(z1[2]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_17 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[1]),
    .E(1'h1),
    .Q(z1[1]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_18 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[0]),
    .E(1'h1),
    .Q(z1[0]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_2 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[16]),
    .E(1'h1),
    .Q(z1[16]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_3 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[15]),
    .E(1'h1),
    .Q(z1[15]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_4 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[14]),
    .E(1'h1),
    .Q(z1[14]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_5 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[13]),
    .E(1'h1),
    .Q(z1[13]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_6 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[12]),
    .E(1'h1),
    .Q(z1[12]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_7 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[11]),
    .E(1'h1),
    .Q(z1[11]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_8 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[10]),
    .E(1'h1),
    .Q(z1[10]),
    .R(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "dsp_simd_post_synth_sim.v:32.5-33.23|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/ffs_map.v:178.12-178.65" *)
  sdffre z1_sdffre_Q_9 (
    .C(clk),
    .D(b1_QL_DSP2_MULT_b_z[9]),
    .E(1'h1),
    .Q(z1[9]),
    .R(1'h1)
  );
endmodule
