/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "bram36k_afifo.v:99.1-138.10" *)
module af4096x9_4096x9(DIN, PUSH, POP, clock0, clock1, Async_Flush, Almost_Full, Almost_Empty, Full, Empty, Full_Watermark, Empty_Watermark, Overrun_Error, Underrun_Error, DOUT);
  (* src = "bram36k_afifo.v:111.20-111.32" *)
  output Almost_Empty;
  wire Almost_Empty;
  (* src = "bram36k_afifo.v:111.8-111.19" *)
  output Almost_Full;
  wire Almost_Full;
  (* src = "bram36k_afifo.v:109.7-109.18" *)
  input Async_Flush;
  wire Async_Flush;
  (* src = "bram36k_afifo.v:108.27-108.30" *)
  input [8:0] DIN;
  wire [8:0] DIN;
  (* src = "bram36k_afifo.v:110.28-110.32" *)
  output [8:0] DOUT;
  wire [8:0] DOUT;
  (* src = "bram36k_afifo.v:112.14-112.19" *)
  output Empty;
  wire Empty;
  (* src = "bram36k_afifo.v:113.24-113.39" *)
  output Empty_Watermark;
  wire Empty_Watermark;
  (* src = "bram36k_afifo.v:118.3-137.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2160.15-2160.25" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] FIFO_INST_RDATA_A1_o;
  (* src = "bram36k_afifo.v:118.3-137.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2159.15-2159.22" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35" *)
  wire [35:0] FIFO_INST_RDATA_B1_o;
  (* src = "bram36k_afifo.v:112.8-112.12" *)
  output Full;
  wire Full;
  (* src = "bram36k_afifo.v:113.8-113.22" *)
  output Full_Watermark;
  wire Full_Watermark;
  (* src = "bram36k_afifo.v:114.8-114.21" *)
  output Overrun_Error;
  wire Overrun_Error;
  (* src = "bram36k_afifo.v:107.12-107.15" *)
  input POP;
  wire POP;
  (* src = "bram36k_afifo.v:107.7-107.11" *)
  input PUSH;
  wire PUSH;
  (* src = "bram36k_afifo.v:114.23-114.37" *)
  output Underrun_Error;
  wire Underrun_Error;
  (* src = "bram36k_afifo.v:106.7-106.13" *)
  input clock0;
  wire clock0;
  (* src = "bram36k_afifo.v:106.14-106.20" *)
  input clock1;
  wire clock1;
  (* is_fifo = 32'd1 *)
  (* is_inferred = 32'd0 *)
  (* is_split = 32'd0 *)
  (* module_not_derived = 32'd1 *)
  (* port_a_dwidth = 32'd9 *)
  (* port_b_dwidth = 32'd9 *)
  (* src = "bram36k_afifo.v:118.3-137.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2226.10-2260.3" *)
  (* sync_fifo = 32'd0 *)
  TDP36K_FIFO_ASYNC_A_X9_B_X9_nonsplit #(
    .MODE_BITS(81'h001402849240140142492)
  ) FIFO_INST (
    .ADDR_A1_i(15'h0000),
    .ADDR_A2_i(14'h0000),
    .ADDR_B1_i(15'h0000),
    .ADDR_B2_i(14'h0000),
    .BE_A1_i(2'h3),
    .BE_A2_i(2'h3),
    .BE_B1_i(2'h3),
    .BE_B2_i(2'h3),
    .CLK_A1_i(clock0),
    .CLK_A2_i(1'h0),
    .CLK_B1_i(clock1),
    .CLK_B2_i(1'h0),
    .FLUSH1_i(Async_Flush),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(FIFO_INST_RDATA_A1_o),
    .RDATA_B1_o({ FIFO_INST_RDATA_B1_o[17], DOUT[8], FIFO_INST_RDATA_B1_o[15:8], DOUT[7:0] }),
    .RDATA_B2_o(FIFO_INST_RDATA_B1_o[35:18]),
    .REN_A1_i(1'h1),
    .REN_A2_i(1'h0),
    .REN_B1_i(POP),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i({ 1'h0, DIN[8], 8'h00, DIN[7:0] }),
    .WDATA_A2_i(18'h00000),
    .WDATA_B1_i(18'h00000),
    .WDATA_B2_i(18'h00000),
    .WEN_A1_i(PUSH),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(1'h0),
    .WEN_B2_i(1'h0)
  );
  assign Almost_Empty = FIFO_INST_RDATA_A1_o[6];
  assign Almost_Full = FIFO_INST_RDATA_A1_o[2];
  assign Empty = FIFO_INST_RDATA_A1_o[7];
  assign Empty_Watermark = FIFO_INST_RDATA_A1_o[5];
  assign { FIFO_INST_RDATA_B1_o[16], FIFO_INST_RDATA_B1_o[7:0] } = DOUT;
  assign Full = FIFO_INST_RDATA_A1_o[3];
  assign Full_Watermark = FIFO_INST_RDATA_A1_o[1];
  assign Overrun_Error = FIFO_INST_RDATA_A1_o[0];
  assign Underrun_Error = FIFO_INST_RDATA_A1_o[4];
endmodule
