/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "bram18k_afifo.v:17.1-56.10" *)
module af1024x18_1024x18(DIN, PUSH, POP, clock0, clock1, Async_Flush, Almost_Full, Almost_Empty, Full, Empty, Full_Watermark, Empty_Watermark, Overrun_Error, Underrun_Error, DOUT);
  (* src = "bram18k_afifo.v:29.20-29.32" *)
  output Almost_Empty;
  wire Almost_Empty;
  (* src = "bram18k_afifo.v:29.8-29.19" *)
  output Almost_Full;
  wire Almost_Full;
  (* src = "bram18k_afifo.v:27.7-27.18" *)
  input Async_Flush;
  wire Async_Flush;
  (* src = "bram18k_afifo.v:26.27-26.30" *)
  input [17:0] DIN;
  wire [17:0] DIN;
  (* src = "bram18k_afifo.v:28.28-28.32" *)
  output [17:0] DOUT;
  wire [17:0] DOUT;
  (* src = "bram18k_afifo.v:30.14-30.19" *)
  output Empty;
  wire Empty;
  (* src = "bram18k_afifo.v:31.24-31.39" *)
  output Empty_Watermark;
  wire Empty_Watermark;
  (* src = "bram18k_afifo.v:36.3-55.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2628.10-2661.3|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_final_map.v:1367.15-1367.26" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] \FIFO_INST.U1_RDATA_A1_o ;
  (* src = "bram18k_afifo.v:36.3-55.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2628.10-2661.3|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_final_map.v:1371.15-1371.26" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] \FIFO_INST.U1_RDATA_A2_o ;
  (* src = "bram18k_afifo.v:36.3-55.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2628.10-2661.3|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_final_map.v:1316.31-1316.36" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] \FIFO_INST.U1_RDATA_B2_o ;
  (* src = "bram18k_afifo.v:30.8-30.12" *)
  output Full;
  wire Full;
  (* src = "bram18k_afifo.v:31.8-31.22" *)
  output Full_Watermark;
  wire Full_Watermark;
  (* src = "bram18k_afifo.v:32.8-32.21" *)
  output Overrun_Error;
  wire Overrun_Error;
  (* src = "bram18k_afifo.v:25.12-25.15" *)
  input POP;
  wire POP;
  (* src = "bram18k_afifo.v:25.7-25.11" *)
  input PUSH;
  wire PUSH;
  (* src = "bram18k_afifo.v:32.23-32.37" *)
  output Underrun_Error;
  wire Underrun_Error;
  (* src = "bram18k_afifo.v:24.7-24.13" *)
  input clock0;
  wire clock0;
  (* src = "bram18k_afifo.v:24.14-24.20" *)
  input clock1;
  wire clock1;
  (* is_fifo = 32'd1 *)
  (* is_inferred = 32'd0 *)
  (* is_split = 32'd0 *)
  (* module_not_derived = 32'd1 *)
  (* port_a_dwidth = 32'd18 *)
  (* port_b_dwidth = 32'd18 *)
  (* src = "bram18k_afifo.v:36.3-55.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2628.10-2661.3|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_final_map.v:1458.10-1492.3" *)
  (* sync_fifo = 32'd0 *)
  TDP36K_FIFO_ASYNC_A1_X18_B1_X18_A2_X18_B2_X18_split #(
    .MODE_BITS(81'h101402852480140142924)
  ) \FIFO_INST.U1  (
    .ADDR_A1_i(15'h0000),
    .ADDR_A2_i(14'h0000),
    .ADDR_B1_i(15'h0000),
    .ADDR_B2_i(14'h0000),
    .BE_A1_i(2'h3),
    .BE_A2_i(2'h3),
    .BE_B1_i(2'h3),
    .BE_B2_i(2'h3),
    .CLK_A1_i(clock0),
    .CLK_A2_i(1'h0),
    .CLK_B1_i(clock1),
    .CLK_B2_i(1'h0),
    .FLUSH1_i(Async_Flush),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(\FIFO_INST.U1_RDATA_A1_o ),
    .RDATA_A2_o(\FIFO_INST.U1_RDATA_A2_o ),
    .RDATA_B1_o(DOUT),
    .RDATA_B2_o(\FIFO_INST.U1_RDATA_B2_o ),
    .REN_A1_i(1'h1),
    .REN_A2_i(1'h1),
    .REN_B1_i(POP),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i(DIN),
    .WDATA_A2_i(18'h00000),
    .WDATA_B1_i(18'h00000),
    .WDATA_B2_i(18'h00000),
    .WEN_A1_i(PUSH),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(1'h0),
    .WEN_B2_i(1'h0)
  );
  assign Almost_Empty = \FIFO_INST.U1_RDATA_A1_o [6];
  assign Almost_Full = \FIFO_INST.U1_RDATA_A1_o [2];
  assign Empty = \FIFO_INST.U1_RDATA_A1_o [7];
  assign Empty_Watermark = \FIFO_INST.U1_RDATA_A1_o [5];
  assign Full = \FIFO_INST.U1_RDATA_A1_o [3];
  assign Full_Watermark = \FIFO_INST.U1_RDATA_A1_o [1];
  assign Overrun_Error = \FIFO_INST.U1_RDATA_A1_o [0];
  assign Underrun_Error = \FIFO_INST.U1_RDATA_A1_o [4];
endmodule
