/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "asymmetric_bram36k_afifo.v:59.1-98.10" *)
module af2048x18_1024x36(DIN, PUSH, POP, clock0, clock1, Async_Flush, Almost_Full, Almost_Empty, Full, Empty, Full_Watermark, Empty_Watermark, Overrun_Error, Underrun_Error, DOUT);
  (* src = "asymmetric_bram36k_afifo.v:71.20-71.32" *)
  output Almost_Empty;
  wire Almost_Empty;
  (* src = "asymmetric_bram36k_afifo.v:71.8-71.19" *)
  output Almost_Full;
  wire Almost_Full;
  (* src = "asymmetric_bram36k_afifo.v:69.7-69.18" *)
  input Async_Flush;
  wire Async_Flush;
  (* src = "asymmetric_bram36k_afifo.v:68.27-68.30" *)
  input [17:0] DIN;
  wire [17:0] DIN;
  (* src = "asymmetric_bram36k_afifo.v:70.28-70.32" *)
  output [35:0] DOUT;
  wire [35:0] DOUT;
  (* src = "asymmetric_bram36k_afifo.v:72.14-72.19" *)
  output Empty;
  wire Empty;
  (* src = "asymmetric_bram36k_afifo.v:73.24-73.39" *)
  output Empty_Watermark;
  wire Empty_Watermark;
  (* src = "asymmetric_bram36k_afifo.v:78.3-97.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2160.15-2160.25" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] FIFO_INST_RDATA_A1_o;
  (* src = "asymmetric_bram36k_afifo.v:72.8-72.12" *)
  output Full;
  wire Full;
  (* src = "asymmetric_bram36k_afifo.v:73.8-73.22" *)
  output Full_Watermark;
  wire Full_Watermark;
  (* src = "asymmetric_bram36k_afifo.v:74.8-74.21" *)
  output Overrun_Error;
  wire Overrun_Error;
  (* src = "asymmetric_bram36k_afifo.v:67.12-67.15" *)
  input POP;
  wire POP;
  (* src = "asymmetric_bram36k_afifo.v:67.7-67.11" *)
  input PUSH;
  wire PUSH;
  (* src = "asymmetric_bram36k_afifo.v:74.23-74.37" *)
  output Underrun_Error;
  wire Underrun_Error;
  (* src = "asymmetric_bram36k_afifo.v:66.7-66.13" *)
  input clock0;
  wire clock0;
  (* src = "asymmetric_bram36k_afifo.v:66.14-66.20" *)
  input clock1;
  wire clock1;
  (* is_fifo = 32'd1 *)
  (* is_inferred = 32'd0 *)
  (* is_split = 32'd0 *)
  (* module_not_derived = 32'd1 *)
  (* port_a_dwidth = 32'd18 *)
  (* port_b_dwidth = 32'd36 *)
  (* src = "asymmetric_bram36k_afifo.v:78.3-97.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2226.10-2260.3" *)
  (* sync_fifo = 32'd0 *)
  TDP36K_FIFO_ASYNC_A_X18_B_X36_nonsplit #(
    .MODE_BITS(81'h00140285a680140142d34)
  ) FIFO_INST (
    .ADDR_A1_i(15'h0000),
    .ADDR_A2_i(14'h0000),
    .ADDR_B1_i(15'h0000),
    .ADDR_B2_i(14'h0000),
    .BE_A1_i(2'h3),
    .BE_A2_i(2'h3),
    .BE_B1_i(2'h3),
    .BE_B2_i(2'h3),
    .CLK_A1_i(clock0),
    .CLK_A2_i(1'h0),
    .CLK_B1_i(clock1),
    .CLK_B2_i(1'h0),
    .FLUSH1_i(Async_Flush),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(FIFO_INST_RDATA_A1_o),
    .RDATA_B1_o(DOUT[17:0]),
    .RDATA_B2_o(DOUT[35:18]),
    .REN_A1_i(1'h1),
    .REN_A2_i(1'h0),
    .REN_B1_i(POP),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i(DIN),
    .WDATA_A2_i(18'h00000),
    .WDATA_B1_i(18'h00000),
    .WDATA_B2_i(18'h00000),
    .WEN_A1_i(PUSH),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(1'h0),
    .WEN_B2_i(1'h0)
  );
  assign Almost_Empty = FIFO_INST_RDATA_A1_o[6];
  assign Almost_Full = FIFO_INST_RDATA_A1_o[2];
  assign Empty = FIFO_INST_RDATA_A1_o[7];
  assign Empty_Watermark = FIFO_INST_RDATA_A1_o[5];
  assign Full = FIFO_INST_RDATA_A1_o[3];
  assign Full_Watermark = FIFO_INST_RDATA_A1_o[1];
  assign Overrun_Error = FIFO_INST_RDATA_A1_o[0];
  assign Underrun_Error = FIFO_INST_RDATA_A1_o[4];
endmodule
