/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "asymmetric_bram36k_sfifo.v:137.1-175.10" *)
module f1024x36_2048x18(DIN, PUSH, POP, clock0, Async_Flush, Almost_Full, Almost_Empty, Full, Empty, Full_Watermark, Empty_Watermark, Overrun_Error, Underrun_Error, DOUT);
  (* src = "asymmetric_bram36k_sfifo.v:149.20-149.32" *)
  output Almost_Empty;
  wire Almost_Empty;
  (* src = "asymmetric_bram36k_sfifo.v:149.8-149.19" *)
  output Almost_Full;
  wire Almost_Full;
  (* src = "asymmetric_bram36k_sfifo.v:147.7-147.18" *)
  input Async_Flush;
  wire Async_Flush;
  (* src = "asymmetric_bram36k_sfifo.v:146.27-146.30" *)
  input [35:0] DIN;
  wire [35:0] DIN;
  (* src = "asymmetric_bram36k_sfifo.v:148.28-148.32" *)
  output [17:0] DOUT;
  wire [17:0] DOUT;
  (* src = "asymmetric_bram36k_sfifo.v:150.14-150.19" *)
  output Empty;
  wire Empty;
  (* src = "asymmetric_bram36k_sfifo.v:151.24-151.39" *)
  output Empty_Watermark;
  wire Empty_Watermark;
  (* src = "asymmetric_bram36k_sfifo.v:156.3-174.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:1971.15-1971.25" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] FIFO_INST_RDATA_A1_o;
  (* src = "asymmetric_bram36k_sfifo.v:156.3-174.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:1970.15-1970.22" *)
  (* unused_bits = "18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35" *)
  wire [35:0] FIFO_INST_RDATA_B2_o;
  (* src = "asymmetric_bram36k_sfifo.v:150.8-150.12" *)
  output Full;
  wire Full;
  (* src = "asymmetric_bram36k_sfifo.v:151.8-151.22" *)
  output Full_Watermark;
  wire Full_Watermark;
  (* src = "asymmetric_bram36k_sfifo.v:152.8-152.21" *)
  output Overrun_Error;
  wire Overrun_Error;
  (* src = "asymmetric_bram36k_sfifo.v:145.12-145.15" *)
  input POP;
  wire POP;
  (* src = "asymmetric_bram36k_sfifo.v:145.7-145.11" *)
  input PUSH;
  wire PUSH;
  (* src = "asymmetric_bram36k_sfifo.v:152.23-152.37" *)
  output Underrun_Error;
  wire Underrun_Error;
  (* src = "asymmetric_bram36k_sfifo.v:144.7-144.13" *)
  input clock0;
  wire clock0;
  (* is_fifo = 32'd1 *)
  (* is_inferred = 32'd0 *)
  (* is_split = 32'd0 *)
  (* module_not_derived = 32'd1 *)
  (* port_a_dwidth = 32'd36 *)
  (* port_b_dwidth = 32'd18 *)
  (* src = "asymmetric_bram36k_sfifo.v:156.3-174.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2041.11-2075.3" *)
  (* sync_fifo = 32'd1 *)
  TDP36K_FIFO_SYNC_A_X36_B_X18_nonsplit #(
    .MODE_BITS(81'h0014028534e01401429a7)
  ) FIFO_INST (
    .ADDR_A1_i(15'h0000),
    .ADDR_A2_i(14'h0000),
    .ADDR_B1_i(15'h0000),
    .ADDR_B2_i(14'h0000),
    .BE_A1_i(2'h3),
    .BE_A2_i(2'h3),
    .BE_B1_i(2'h3),
    .BE_B2_i(2'h3),
    .CLK_A1_i(clock0),
    .CLK_A2_i(1'h0),
    .CLK_B1_i(clock0),
    .CLK_B2_i(1'h0),
    .FLUSH1_i(Async_Flush),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(FIFO_INST_RDATA_A1_o),
    .RDATA_B1_o(DOUT),
    .RDATA_B2_o(FIFO_INST_RDATA_B2_o[35:18]),
    .REN_A1_i(1'h1),
    .REN_A2_i(1'h0),
    .REN_B1_i(POP),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i(DIN[17:0]),
    .WDATA_A2_i(DIN[35:18]),
    .WDATA_B1_i(18'h00000),
    .WDATA_B2_i(18'h00000),
    .WEN_A1_i(PUSH),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(1'h0),
    .WEN_B2_i(1'h0)
  );
  assign Almost_Empty = FIFO_INST_RDATA_A1_o[6];
  assign Almost_Full = FIFO_INST_RDATA_A1_o[2];
  assign Empty = FIFO_INST_RDATA_A1_o[7];
  assign Empty_Watermark = FIFO_INST_RDATA_A1_o[5];
  assign FIFO_INST_RDATA_B2_o[17:0] = DOUT;
  assign Full = FIFO_INST_RDATA_A1_o[3];
  assign Full_Watermark = FIFO_INST_RDATA_A1_o[1];
  assign Overrun_Error = FIFO_INST_RDATA_A1_o[0];
  assign Underrun_Error = FIFO_INST_RDATA_A1_o[4];
endmodule
