/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 11.2.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "asymmetric_bram36k_sfifo.v:97.1-135.10" *)
module f2048x18_4098x9(DIN, PUSH, POP, clock0, Async_Flush, Almost_Full, Almost_Empty, Full, Empty, Full_Watermark, Empty_Watermark, Overrun_Error, Underrun_Error, DOUT);
  (* src = "asymmetric_bram36k_sfifo.v:109.20-109.32" *)
  output Almost_Empty;
  wire Almost_Empty;
  (* src = "asymmetric_bram36k_sfifo.v:109.8-109.19" *)
  output Almost_Full;
  wire Almost_Full;
  (* src = "asymmetric_bram36k_sfifo.v:107.7-107.18" *)
  input Async_Flush;
  wire Async_Flush;
  (* src = "asymmetric_bram36k_sfifo.v:106.27-106.30" *)
  input [17:0] DIN;
  wire [17:0] DIN;
  (* src = "asymmetric_bram36k_sfifo.v:108.28-108.32" *)
  output [8:0] DOUT;
  wire [8:0] DOUT;
  (* src = "asymmetric_bram36k_sfifo.v:110.14-110.19" *)
  output Empty;
  wire Empty;
  (* src = "asymmetric_bram36k_sfifo.v:111.24-111.39" *)
  output Empty_Watermark;
  wire Empty_Watermark;
  (* src = "asymmetric_bram36k_sfifo.v:116.3-134.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:1971.15-1971.25" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] FIFO_INST_RDATA_A1_o;
  (* src = "asymmetric_bram36k_sfifo.v:116.3-134.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:1970.15-1970.22" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35" *)
  wire [35:0] FIFO_INST_RDATA_B1_o;
  (* src = "asymmetric_bram36k_sfifo.v:110.8-110.12" *)
  output Full;
  wire Full;
  (* src = "asymmetric_bram36k_sfifo.v:111.8-111.22" *)
  output Full_Watermark;
  wire Full_Watermark;
  (* src = "asymmetric_bram36k_sfifo.v:112.8-112.21" *)
  output Overrun_Error;
  wire Overrun_Error;
  (* src = "asymmetric_bram36k_sfifo.v:105.12-105.15" *)
  input POP;
  wire POP;
  (* src = "asymmetric_bram36k_sfifo.v:105.7-105.11" *)
  input PUSH;
  wire PUSH;
  (* src = "asymmetric_bram36k_sfifo.v:112.23-112.37" *)
  output Underrun_Error;
  wire Underrun_Error;
  (* src = "asymmetric_bram36k_sfifo.v:104.7-104.13" *)
  input clock0;
  wire clock0;
  (* is_fifo = 32'd1 *)
  (* is_inferred = 32'd0 *)
  (* is_split = 32'd0 *)
  (* module_not_derived = 32'd1 *)
  (* port_a_dwidth = 32'd18 *)
  (* port_b_dwidth = 32'd9 *)
  (* src = "asymmetric_bram36k_sfifo.v:116.3-134.18|/localproj/lsharma/opt/yosys-v0.55/bin/../share/yosys/quicklogic/qlf_k6n10f/brams_map.v:2041.11-2075.3" *)
  (* sync_fifo = 32'd1 *)
  TDP36K_FIFO_SYNC_A_X18_B_X9_nonsplit #(
    .MODE_BITS(81'h00140284a2a0140142515)
  ) FIFO_INST (
    .ADDR_A1_i(15'h0000),
    .ADDR_A2_i(14'h0000),
    .ADDR_B1_i(15'h0000),
    .ADDR_B2_i(14'h0000),
    .BE_A1_i(2'h3),
    .BE_A2_i(2'h3),
    .BE_B1_i(2'h3),
    .BE_B2_i(2'h3),
    .CLK_A1_i(clock0),
    .CLK_A2_i(1'h0),
    .CLK_B1_i(clock0),
    .CLK_B2_i(1'h0),
    .FLUSH1_i(Async_Flush),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(FIFO_INST_RDATA_A1_o),
    .RDATA_B1_o({ FIFO_INST_RDATA_B1_o[17], DOUT[8], FIFO_INST_RDATA_B1_o[15:8], DOUT[7:0] }),
    .RDATA_B2_o(FIFO_INST_RDATA_B1_o[35:18]),
    .REN_A1_i(1'h1),
    .REN_A2_i(1'h0),
    .REN_B1_i(POP),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i(DIN),
    .WDATA_A2_i(18'h00000),
    .WDATA_B1_i(18'h00000),
    .WDATA_B2_i(18'h00000),
    .WEN_A1_i(PUSH),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(1'h0),
    .WEN_B2_i(1'h0)
  );
  assign Almost_Empty = FIFO_INST_RDATA_A1_o[6];
  assign Almost_Full = FIFO_INST_RDATA_A1_o[2];
  assign Empty = FIFO_INST_RDATA_A1_o[7];
  assign Empty_Watermark = FIFO_INST_RDATA_A1_o[5];
  assign { FIFO_INST_RDATA_B1_o[16], FIFO_INST_RDATA_B1_o[7:0] } = DOUT;
  assign Full = FIFO_INST_RDATA_A1_o[3];
  assign Full_Watermark = FIFO_INST_RDATA_A1_o[1];
  assign Overrun_Error = FIFO_INST_RDATA_A1_o[0];
  assign Underrun_Error = FIFO_INST_RDATA_A1_o[4];
endmodule
